version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-imovel
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: aluguelimovel
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: