CREATE TABLE imovel
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    endereco        VARCHAR(100)                            NOT NULL,
    valor_aluguel   DOUBLE PRECISION                        NOT NULL,
    proprietario_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_imovel PRIMARY KEY (id)
);

ALTER TABLE imovel
    ADD CONSTRAINT FK_IMOVEL_ON_PROPRIETARIO FOREIGN KEY (proprietario_id) REFERENCES proprietario (id);